test data (200, 4, 4) loaded
Traceback (most recent call last):
  File "main.py", line 176, in <module>
    start_test()
  File "main.py", line 158, in start_test
    model.load_state_dict(torch.load(args.test_chkpt))
  File "D:\anaconda\envs\lsap\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\anaconda\envs\lsap\lib\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\anaconda\envs\lsap\lib\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '.trained_net_exp4.pth'
